apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/flaskmonitor-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: PYTHONUNBUFFERED
              value: "1"
          image: app
          name: app
          ports:
            - containerPort: 9099
              hostPort: 9099
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
